---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# elector

<!-- badges: start -->
<!-- badges: end -->

The goal of elector is to run the elections for AIMOS.

- `elector.R` contains a script that runs a mock election for all offices (for which there are ballots). 

- `AIMOS_2020_Election_Test.csv` contains the raw test ballots on which it depends.

- `meta_election.csv` contains the metadata which allows cleaning of the test data.

- `test-election.qsf` contains a qualtrics survey file that provides a scaffold for ballot collection.

## Election information

Election rules are in the by-laws at the website aimos.community

2021 is the first year where members are elected to the Board rather than to specific offices
all 9 spots are up for grabs.
President, Vice-president, Treasurer, Secretary, Student representative, Diversity&Inclusion are all elected by the Executive Committee after the Committee are elected from the membership

If using Qualtrics for the election, set the survey to invitation only
To edit your survey distribution options, select Survey options > Security > Survey access.
